name: flutterexpension
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.5.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  supabase: ^2.3.0
  fluttertoast: ^8.2.8
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/intersemibold400.ttf
          weight: 400
        - asset: assets/fonts/interbold700.ttf
          weight: 700
        - asset: assets/fonts/interregular400.ttf
          weight: 400
        - asset: assets/fonts/intermedium500.ttf
          weight: 500
